# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup protoc
        # You may pin to the exact commit or the version.
        # uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3
        uses: arduino/setup-protoc@v1.1.2
      - name: Check protoc version
        run: protoc --version
      - name: Check protoc version
        run: pwd
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
      - name: install grpc web
        run: curl -L /usr/local/bin/protoc-gen-grpc-web https://github.com/grpc/grpc-web/releases/download/1.3.1/protoc-gen-grpc-web-1.3.1-linux-x86_64
      - name: show proto
        run: ls .
      - name: generate js proto
        run: protoc -I=./proto \
            --js_out=import_style=commonjs,binary:./proto \
            --grpc-web_out=import_style=typescript,mode=grpcweb:./proto
